apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-resources-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: access-resources
  apiGroup: rbac.authorization.k8s.io
