# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: websocket
# spec:
#   scaleTargetRef:
#     kind: StatefulSet
#     name: websocket
#   pollingInterval: 5
#   cooldownPeriod:  5
#   minReplicaCount: 1
#   maxReplicaCount: 6
#   triggers:
#     - type: prometheus
#       metadata:
#         serverAddress: http://prometheus-server.prometheus.svc
#         metricName: websockets_connections_total
#         # threshold: '9'
#         # query: sum(websockets_connections_total{app="websocket"})
#         # query: max by (pod) (websockets_connections_total{app='websocket'})
